---
- name: "Get ceph mon metadata"
  tags: latex.ceph.mon
  ansible.builtin.command: ceph mon metadata
  become: true
  run_once: true
  register: ceph_mon

- tags: latex.ceph.mon
  debug:
    msg: "{{ ceph_mon['stdout'] }}"
  run_once: true

- name: "Save ceph mon info in {{ latex_ceph_mon['path'] | default(latex_ceph_mon['caption']+'.tex') }}"
  tags: latex.ceph.mon
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_mon['path'] | default(latex_ceph_mon['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_mon['caption'] }}"
    block: "{{ lookup('template','ceph/mon.ji2') }}"
  run_once: true
  connection: local
