---
- name: "Include config dump task from ceph role."
  tags:
    - latex.ceph.dump.daemon.image
    - latex.ceph.dump.daemon.placement
    - latex.ceph.dump.daemon
    - latex.ceph.dump.config
    - latex.ceph.dump.filesystem
    - latex.ceph.dump.pool
    - latex.ceph.dump.osd
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.include_role:
    name: ceph
    tasks_from: dump.yaml

- name: "Include metadata task from ceph role."
  tags:
    - latex.ceph.metadata.mon
    - latex.ceph.metadata.osd
    - latex.ceph.metadata.mds
    - latex.ceph.metadata.mgr
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.include_role:
    name: ceph
    tasks_from: metadata.yaml


- name: "Save latex ceph medatada mon."
  tags:
    - latex.ceph.metadata.mon
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_metadata_mon['path']
      | default(latex_ceph_metadata_mon['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_metadata_mon['marker']
      | default(latex_ceph_metadata_mon['caption']) }}
    block: "{{ lookup('template', 'ceph/metadata/mon.ji2') }}"
  connection: local

- name: "Save latex ceph medatada osd."
  tags:
    - latex.ceph.metadata.osd
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_metadata_osd['path']
      | default(latex_ceph_metadata_osd['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_metadata_osd['marker']
      | default(latex_ceph_metadata_osd['caption']) }}
    block: "{{ lookup('template', 'ceph/metadata/osd.ji2') }}"
  connection: local

- name: "Save latex ceph medatada mds."
  tags:
    - latex.ceph.metadata.mds
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_metadata_mds['path']
      | default(latex_ceph_metadata_mds['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_metadata_mds['marker']
      | default(latex_ceph_metadata_mds['caption']) }}
    block: "{{ lookup('template', 'ceph/metadata/mds.ji2') }}"
  connection: local

- name: "Save latex ceph medatada mgr."
  tags:
    - latex.ceph.metadata.mgr
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_metadata_mgr['path']
      | default(latex_ceph_metadata_mgr['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_metadata_mgr['marker']
      | default(latex_ceph_metadata_mgr['caption']) }}
    block: "{{ lookup('template', 'ceph/metadata/mgr.ji2') }}"
  connection: local

- name: "Save latex ceph dump config."
  tags:
    - latex.ceph.dump.config
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_dump_config['path']
      | default(latex_ceph_dump_config['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_dump_config['marker']
      | default(latex_ceph_dump_config['caption']) }}
    block: "{{ lookup('template', 'ceph/dump/config.ji2') }}"
  connection: local

- name: "Save latex ceph dump daemon image."
  tags:
    - latex.ceph.dump.daemon.image
    - latex.ceph.dump.daemon
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_dump_daemon_image['path']
      | default(latex_ceph_dump_daemon_image['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_dump_daemon_image['marker']
      | default(latex_ceph_dump_daemon_image['caption']) }}
    block: "{{ lookup('template', 'ceph/dump/daemon-image.ji2') }}"
  connection: local

- name: "Save latex ceph dump daemon placement."
  tags:
    - latex.ceph.dump.daemon.placement
    - latex.ceph.dump.daemon
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_dump_daemon_placement['path']
      | default(latex_ceph_dump_daemon_placement['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_dump_daemon_placement['marker']
      | default(latex_ceph_dump_daemon_placement['caption']) }}
    block: "{{ lookup('template', 'ceph/dump/daemon-placement.ji2') }}"
  connection: local

- name: "Save latex ceph dump osd."
  tags:
    - latex.ceph.dump.osd
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_dump_osd['path']
      | default(latex_ceph_dump_osd['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_dump_osd['marker']
      | default(latex_ceph_dump_osd['caption']) }}
    block: "{{ lookup('template', 'ceph/dump/osd.ji2') }}"
  connection: local

- name: "Save latex ceph dump pool."
  tags:
    - latex.ceph.dump.pool
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_dump_pool['path']
      | default(latex_ceph_dump_pool['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_dump_pool['marker']
      | default(latex_ceph_dump_pool['caption']) }}
    block: "{{ lookup('template', 'ceph/dump/pool.ji2') }}"
  connection: local

- name: "Save latex ceph dump filesystem."
  tags:
    - latex.ceph.dump.filesystem
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: >-
      {{ latex_ceph_dump_filesystem['path']
      | default(latex_ceph_dump_filesystem['caption'] + '.tex') }}
    create: true
    mode: "{{ latex_file['mode'] }}"
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: >-
      {mark}{table} % {{ latex_ceph_dump_filesystem['marker']
      | default(latex_ceph_dump_filesystem['caption']) }}
    block: "{{ lookup('template', 'ceph/dump/filesystem.ji2') }}"
  connection: local
