---
- name: "Include config dump task from ceph role."
  tags:
    - latex.ceph.dump.config
    - latex.ceph.dump.osd
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.include_role:
    name: ceph
    tasks_from: dump.yaml

- name: "Include metadata task from ceph role."
  tags:
    - latex.ceph.metadata.mon
    - latex.ceph.metadata.osd
    - latex.ceph.metadata.mds
    - latex.ceph.metadata.mgr
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.include_role:
    name: ceph
    tasks_from: metadata.yaml


- name: "Save ceph mon info in {{ latex_ceph_metadata_mon['path'] | default(latex_ceph_metadata_mon['caption']+'.tex') }}"
  tags:
    - latex.ceph.metadata.mon
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_metadata_mon['path'] | default(latex_ceph_metadata_mon['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_metadata_mon['marker'] | default(latex_ceph_metadata_mon['caption']) }}"
    block: "{{ lookup('template','ceph/metadata/mon.ji2') }}"
  run_once: true
  connection: local

- name: "Save ceph osd info in {{ latex_ceph_metadata_osd['path'] | default(latex_ceph_metadata_osd['caption']+'.tex') }}"
  tags:
    - latex.ceph.metadata.osd
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_metadata_osd['path'] | default(latex_ceph_metadata_osd['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_metadata_osd['marker'] | default(latex_ceph_metadata_osd['caption']) }}"
    block: "{{ lookup('template','ceph/metadata/osd.ji2') }}"
  run_once: true
  connection: local

- name: "Save ceph mds info in {{ latex_ceph_metadata_mds['path'] | default(latex_ceph_metadata_mds['caption']+'.tex') }}"
  tags:
    - latex.ceph.metadata.mds
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_metadata_mds['path'] | default(latex_ceph_metadata_mds['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_metadata_mds['marker'] | default(latex_ceph_metadata_mds['caption']) }}"
    block: "{{ lookup('template','ceph/metadata/mds.ji2') }}"
  run_once: true
  connection: local

- name: "Save ceph mgr info in {{ latex_ceph_metadata_mgr['path'] | default(latex_ceph_metadata_mgr['caption']+'.tex') }}"
  tags:
    - latex.ceph.metadata.mgr
    - latex.ceph.metadata
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_metadata_mgr['path'] | default(latex_ceph_metadata_mgr['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_metadata_mgr['marker'] | default(latex_ceph_metadata_mgr['caption']) }}"
    block: "{{ lookup('template','ceph/metadata/mgr.ji2') }}"
  run_once: true
  connection: local

- name: "Save ceph config dump in {{ latex_ceph_dump_config['path'] | default(latex_ceph_dump_config['caption']+'.tex') }}"
  tags:
    - latex.ceph.dump.config
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_dump_config['path'] | default(latex_ceph_dump_config['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_dump_config['marker'] | default(latex_ceph_dump_config['caption']) }}"
    block: "{{ lookup('template','ceph/dump/config.ji2') }}"
  run_once: true
  connection: local

- name: "Save ceph osd dump in {{ latex_ceph_dump_osd['path'] | default(latex_ceph_dump_osd['caption']+'.tex') }}"
  tags:
    - latex.ceph.dump.osd
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_dump_osd['path'] | default(latex_ceph_dump_osd['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_dump_osd['marker'] | default(latex_ceph_dump_osd['caption']) }}"
    block: "{{ lookup('template','ceph/dump/osd.ji2') }}"
  run_once: true
  connection: local

- name: "Save ceph pool dump in {{ latex_ceph_dump_pool['path'] | default(latex_ceph_dump_pool['caption']+'.tex') }}"
  tags:
    - latex.ceph.dump.pool
    - latex.ceph.dump
    - latex.ceph
  ansible.builtin.blockinfile:
    path: "{{ latex_ceph_dump_pool['path'] | default(latex_ceph_dump_pool['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_ceph_dump_pool['marker'] | default(latex_ceph_dump_pool['caption']) }}"
    block: "{{ lookup('template','ceph/dump/pool.ji2') }}"
  run_once: true
  connection: local
