---
- name: "LaTeX output for VMware"
  tags:
    - latex
    - latex.vmware
  ansible.builtin.import_tasks: vmware.yaml

- name: "LaTeX output for system"
  tags:
    - latex
    - latex.system
  ansible.builtin.import_tasks: system.yaml

- name: "LaTeX output for docker"
  tags:
    - latex
    - latex.docker
  ansible.builtin.import_tasks: docker.yaml
