---
- name: "Import guest info task from vmware role."
  tags:
    - latex.vmware.guest
    - latex.vmware.guest.hardware
    - latex.vmware.guest.network
  ansible.builtin.import_role:
    name: vmware
    tasks_from: guest_info.yaml
- name: "Import guest disk info task from vmware role."
  tags:
    - latex.vmware.guest
    - latex.vmware.guest.hardware
  ansible.builtin.import_role:
    name: vmware
    tasks_from: guest_disk_info.yaml


- name: "Save VMware cluster info in {{ latex_vmware_cluster['path'] | default(latex_vmware_cluster['caption']+'.tex') }}"
  tags: latex.vmware.cluster
  ansible.builtin.blockinfile:
    path: "{{ latex_vmware_cluster['path'] | default(latex_vmware_cluster['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_vmware_cluster['marker'] | default(latex_vmware_cluster['caption']) }}"
    block: "{{ lookup('template','vmware/cluster.ji2') }}"
  run_once: true
  connection: "{{ conn | default('local') }}"

- name: "Save VMware datastore in {{ latex_vmware_datastore['path'] | default(latex_vmware_datastore['caption']+'.tex') }}"
  tags: latex.vmware.datastore
  ansible.builtin.blockinfile:
    path: "{{ latex_vmware_datastore['path'] | default(latex_vmware_datastore['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_vmware_datastore['marker'] | default(latex_vmware_datastore['caption']) }}"
    block: "{{ lookup('template','vmware/datastore.ji2') }}"
  run_once: true
  connection: "{{ conn | default('local') }}"

- name: "Save VMware vswitch info in {{ latex_vmware_vswitch['path'] | default(latex_vmware_vswitch['caption']+'.tex') }}"
  tags: latex.vmware.vswitch
  ansible.builtin.blockinfile:
    path: "{{ latex_vmware_vswitch['path'] | default(latex_vmware_vswitch['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_vmware_vswitch['marker'] | default(latex_vmware_vswitch['caption']) }}"
    block: "{{ lookup('template','vmware/vswitch.ji2') }}"
  run_once: true
  connection: "{{ conn | default('local') }}"

- name: "Save VMware guest hardware info in {{ latex_vmware_guest_hardware['path'] | default(latex_vmware_guest_hardware['caption']+'.tex') }}"
  tags:
    - latex.vmware.guest
    - latex.vmware.guest.hardware
  ansible.builtin.blockinfile:
    path: "{{ latex_vmware_guest_hardware['path'] | default(latex_vmware_guest_hardware['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{table} % {{ latex_vmware_guest_hardware['marker'] | default(latex_vmware_guest_hardware['caption']) }}"
    block: "{{ lookup('template','vmware/guest_hardware.ji2') }}"
  run_once: true
  connection: "{{ conn | default('local') }}"

- name: "Save VMware guest network info in {{ latex_vmware_guest_network['path'] | default(latex_vmware_guest_network['caption']+'.tex') }}"
  tags:
    - latex.vmware.guest
    - latex.vmware.guest.network
  ansible.builtin.blockinfile:
    path: "{{ latex_vmware_guest_network['path'] | default(latex_vmware_guest_network['caption']+'.tex') }}"
    create: true
    marker_begin: '\\begin'
    marker_end: '\\end'
    marker: "{mark}{longtable} % {{ latex_vmware_guest_network['marker'] | default(latex_vmware_guest_network['caption']) }}"
    block: "{{ lookup('template','vmware/guest_network.ji2') }}"
  run_once: true
  connection: "{{ conn | default('local') }}"
